# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Oxford Hack 2019
email: committee@oxfordhack.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Join us this November to build something brilliant at Oxford University's largest student hackathon.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://oxfordhack.co.uk" # the base hostname & protocol for your site
facebook_url: "https://facebook.com/OxfordHack2019/"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
exclude: ["README.md", vendor]

# Sitemap
sitemap:
    filename: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
        - "/register-confirm/"
        - "/css/main.scss"
        - "/register-confirm.html"
